### ISSUE TITLE
chart crash?

### ISSUE THREAD

**Issue by imdumlol** [Yoshubs/Forever-1.0-Hybrid#3]
![Screenshot (9)](https://user-images.githubusercontent.com/118001986/208286923-a4252a60-8761-4a46-961e-c2367a3219e2.png)

**Comment by BeastlyGhost** [comment]
this should fix it

https://github.com/Yoshubs/Forever-1.0-Hybrid/blob/9b7eac011ed7a9d31fc0c3b28208676b807c2ba4/source/states/charting/ChartingState.hx#L253

**Comment by imdumlol** [comment]
![Screenshot (10)](https://user-images.githubusercontent.com/118001986/208314339-2230469f-9b6f-483a-a754-535486f18651.png)

**Comment by imdumlol** [comment]
uh oh

**Comment by imdumlol** [comment]
it does not load

**Comment by imdumlol** [comment]
hello?

**Comment by imdumlol** [comment]
got it up and running

**Comment by imdumlol** [comment]
bruh
![Screenshot (11)](https://user-images.githubusercontent.com/118001986/208316846-8997d425-8f8d-4e1e-8881-75f66f38fe7e.png)

**Comment by imdumlol** [comment]
hello?

**Comment by imdumlol** [comment]
hello?

**Comment by YoshiGames64** [comment]
they moved to legacy lol

**Comment by imdumlol** [comment]
hello?

**Comment by imdumlol** [comment]
hilo?

**Comment by imdumlol** [comment]
heeeeeeeeeeeellllllllllllllllllllooooooooooooooooo?

**Comment by imdumlol** [comment]
bruh
